[package]
edition = "2024"
name = "skse-rust-template"
version = "0.1.0"
license = "ParityLicense-7.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
chardet = "0.2.4"
cxx = { version = "1.0.143", features = ["c++20"] }
encoding-next = "0.3.0"
log = "0.4.20"
rust-ini = "0.21.1"
simplelog = "0.12.2"

[build-dependencies]
cxx-build = "1.0.143"

[profile.release]
debug = true
lto = true
codegen-units = 1
